directories:
  output: dist_electron
  buildResources: assets
appId: com.official-electron-vue.app
productName: Electron Vue
copyright: Copyright © 2022 ${author}
publish:
  - provider: github
    owner: Bible-Projects
nsis:
  oneClick: true
  allowToChangeInstallationDirectory: false
  deleteAppDataOnUninstall: true
files:
  - filter:
      - dist/**/*
extraResources:
  - filter:
      - defaults/**/*
electronVersion: 22.0.0
